---
new_page_extension: md
auto_deploy: true
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: gridsome build
  preview_output_directory: ".vuepress/dist"
  output_directory: dist
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
